### ISSUE TITLE
No such module 'TOCropViewController'

### ISSUE THREAD

**Issue by burakios** [Imputes/Instagram#8]
Hello,

I getting this error on CropViewController.swift file. How can i solve this problem?
Thanks

**Comment by Imputes** [comment]
Hello, may be you hadn't added TOCropViewController .h and .m Objc files before.

**Comment by burakios** [comment]
Thanks for the return but where and how can I add?  Can you help me please?

**Comment by Imputes** [comment]
They just exist in this repo page list, named "TOCropViewController".  
Click it and you will see Models, Views, TOCropViewController.h and TOCropViewController.m , add those files. Then 
```swift
import TOCropViewController
```

**Comment by burakios** [comment]
I've already added. but I'm getting the same error.
look it: https://ibb.co/dwcKew

**Comment by DhruvKalaria** [comment]
Remove the import TOCropViewController statement and add #import "TOCropViewController.h" to Instagram-Bridging-Header.h file that should solve your issue.
Thanks !

**Comment by focusspan** [comment]
@DhruvKalaria I follow your guide and that solve my issue also. Thanks.

**Comment by burakios** [comment]
@DhruvKalaria solved this problem. Thank you
